import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


//* Font Geint Sans
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

//* Font Geist Mono
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


//* Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//* Root Layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
